#1. 使用git-sync clone一个git仓库到volume中
#2. 使用Kaniko/buildkit构建docker镜像
#3. 推送docker镜像到镜像仓库

#git-secret:
#kubectl create secret generic git-creds \
#     --from-file=ssh=$HOME/.ssh/id_rsa \
#     --from-file=known_hosts=$HOME/.ssh/known_hosts 

#docker-secret:
#kubectl create secret generic docker-secret --from-file=config.json=$HOME/.docker/config.json 
#config.json 类似于：
#{"auths": {"https://index.docker.io/v1/": {"username":"USERNAME","password":"PASSWORD"},}}
#或者 echo "USERNAME":"PASSWORD" | base64 ,将输出写入config.json:
#{"auths": {"https://index.docker.io/v1/": {"auth":"上一步的输出"}}


#kubectl label node cn-hangzhou.172.20.223.208 argo-worflow="true"
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: ci-test
spec:
  entrypoint: pipeline
  #mount secrets for the workflow
  volumes:
    - name: git-secret
      secret:
        defaultMode: 256
        secretName: git-creds # your-ssh-key
    - name: repo-root
      hostPath:
        path: /tmp/ci-test
        type: DirectoryOrCreate
    - name: docker-secret
      secret:
        secretName: docker-secret
  nodeSelector:
      argo-worflow: "true"
  hostNetwork: true
  #start the sequence
  templates:
    - name: pipeline
      dag:
        tasks:
          - name: git-sync
            template: git-sync
          - name: check-repo
            template: check-repo
            depends: git-sync
          - name: build-docker
            template: build-docker 
            depends: check-repo
    - name: check-repo
      container:
        image: alpine:latest
        command: [sh, -c]
        args:
          [
            "echo getting message from volume; ls /workdir/root/argo-workflow-guide > ls.txt; cat ls.txt",
          ]
        volumeMounts:
          - name: repo-root
            mountPath: /workdir ##
          - name: git-secret
            mountPath: /etc/git-secret ##
    - name: build-docker
      container:
        #argo is gonna ask for a command - the debug version allows us to exec this way i think
        image: docker.io/chriskery/executor:v1.9.0
        imagePullPolicy: Always
        env:
          - name: DOCKER_USERNAME
            value: chriskery
          - name: DOCKER_PASSWORD
            value: 1584537639qq
        command: ["/kaniko/executor"]
        # (if we set cache true we should make an ECR container update)
        # i gave the full path to the docker file but maybe relative is fine
        args:
          [
            "--context=/workdir/root/argo-workflow-guide",
            "--destination=docker.io/chriskery/argo-worflow-guide:v1",
            "--cache=false",
          ]
        volumeMounts:
          - name: repo-root
            mountPath: /workdir ##
          - name: docker-secret
            mountPath: /kaniko/.docker
        resources:
          limits:
            cpu: 1
            memory: 5Gi
    - name: git-sync
      container:
        image: docker.io/chriskery/git-sync:v3.1.6
        args:
          - "--repo=git@github.com:chriskery/argo-workflow-guide.git"
          - "--root=/workdir/root"
          - "--dest=argo-workflow-guide"
          - "--max-sync-failures=3"
          - "--timeout=200"
          - "--branch=main"
          - "--ssh"
          - "--one-time"
        command: ["/git-sync"]
        name: git-data
        volumeMounts:
          - name: repo-root
            mountPath: /workdir ##
          - name: git-secret
            mountPath: /etc/git-secret
      securityContext:
        runAsUser: 0 # to allow read of ssh key